TRANSLATIONS = {
    "EN": {
        # Sidebar
        "nav_dash": "🏠 Dashboard",
        "nav_macro": "⚡ Macros",
        "nav_config": "⚙️ Config",
        "status_standby": "● STANDBY",
        "status_rec": "● RECORDING",
        "made_by": "Made by Shushi",
        
        # Dashboard
        "greeting_morning": "☀️ Good Morning Shushi",
        "greeting_afternoon": "🌤️ Good Afternoon",
        "greeting_evening": "🌙 Good Evening Shushi",
        "card_time": "TIME",
        "card_events": "EVENTS",
        "card_mode": "MODE",
        "hk_info": "⌨️ F1: Play | F2: Rec | F3: Ghost",
        "btn_rec": "🔴 REC (F2)",
        "btn_stop_rec": "⏹ STOP REC",
        "btn_play": "▶ PLAY (F1)",
        "btn_stop_play": "⏸ STOP PLAY",
        "logs_title": "📊 LOGS",
        "log_init": "[System] Interface loaded.",
        "mode_play": "⏱️ Playback Mode:",
        "infinite": "Infinite Loop",
        "duration": "Or Duration (min):",
        "duration_lbl": "Duration:",
        "cycle": "1 Cycle",
        
        # Macros Page
        "title_macro": "⚡ MACRO MANAGER",
        "btn_save": "💾 Save Macro",
        "btn_load": "▶ Load & Use Selected",
        "list_label": "📁 Available Macros (Double-click to load):",
        "btn_refresh": "🔄 Refresh List",
        "log_saved": "💾 Macro saved:",
        "log_loaded": "📂 Macro loaded:",
        "err_save": "Error saving:",
        "err_load": "Error loading:",
        "warn_select": "Please select a macro first.",
        "warn_empty": "Nothing to save! Record a macro first.",
        
        # Config Page
        "title_config": "⚙️ CONFIGURATION",
        "grp_lang": "🌍 Language",
        "lbl_lang": "Select Language:",
        "grp_theme": "🎨 Appearance",
        "lbl_theme": "Select Theme:",
        "grp_opacity": "👻 Transparency",
        "grp_mode": "📹 Recording Mode",
        "rb_lite": "Lite (Clicks + Keys only)",
        "rb_pro": "Pro (Full Mouse Movements)",
        "grp_hk": "⌨️ Keyboard Shortcuts",
        "log_theme": "🎨 Theme applied:",
        "log_mode": "⚙️ Mode changed:",
        "log_lang": "🌍 Language changed to English",
        
        # Messages
        "msg_rec_start": "🔴 Recording started",
        "msg_rec_end": "✅ Recording finished:",
        "msg_play_start": "▶ Playing macro...",
        "msg_play_end": "⏸ Macro finished",
        "msg_ghost_on": "👻 Ghost Mode ON (Press F3 to show)",
        "msg_ghost_off": "👁️ Ghost Mode OFF",
        "err_conflict_rec": "⚠️ Cannot record while playing!",
        "err_conflict_play": "⚠️ Cannot play while recording!",
        "err_no_data": "No macro in memory to play."
    },
    
    "FR": {
        # Sidebar
        "nav_dash": "🏠 Accueil",
        "nav_macro": "⚡ Macros",
        "nav_config": "⚙️ Config",
        "status_standby": "● EN ATTENTE",
        "status_rec": "● ENREGISTREMENT",
        "made_by": "Made by Shushi",
        
        # Dashboard
        "greeting_morning": "☀️ Bonjour Shushi",
        "greeting_afternoon": "🌤️ Bon après-midi",
        "greeting_evening": "🌙 Bonsoir Shushi",
        "card_time": "HEURE",
        "card_events": "ACTIONS",
        "card_mode": "MODE",
        "hk_info": "⌨️ F1: Play | F2: Rec | F3: Ghost",
        "btn_rec": "🔴 REC (F2)",
        "btn_stop_rec": "⏹ STOP REC",
        "btn_play": "▶ PLAY (F1)",
        "btn_stop_play": "⏸ STOP PLAY",
        "logs_title": "📊 JOURNAUX",
        "log_init": "[Système] Interface chargée.",
        "mode_play": "⏱️ Mode de lecture :",
        "infinite": "Boucle Infinie",
        "duration": "Ou Durée (min) :",
        "duration_lbl": "Durée :",
        "cycle": "1 Cycle",
        
        # Macros Page
        "title_macro": "⚡ GESTION MACROS",
        "btn_save": "💾 Sauvegarder une macro",
        "btn_load": "▶ Utiliser la macro sélectionnée",
        "list_label": "📁 Macros disponibles (Double-clic pour charger) :",
        "btn_refresh": "🔄 Rafraîchir la liste",
        "log_saved": "💾 Macro sauvegardée :",
        "log_loaded": "📂 Macro chargée :",
        "err_save": "Erreur lors de la sauvegarde :",
        "err_load": "Impossible de charger la macro :",
        "warn_select": "Veuillez sélectionner une macro dans la liste.",
        "warn_empty": "Rien à sauvegarder ! Enregistrez d'abord une macro.",
        
        # Config Page
        "title_config": "⚙️ CONFIGURATION",
        "grp_lang": "🌍 Langue",
        "lbl_lang": "Choisir la langue :",
        "grp_theme": "🎨 Apparence",
        "lbl_theme": "Choisir un thème :",
        "grp_opacity": "👻 Transparence",
        "grp_mode": "📹 Mode d'enregistrement",
        "rb_lite": "Lite (Clics + Clavier uniquement)",
        "rb_pro": "Pro (Mouvements de souris complets)",
        "grp_hk": "⌨️ Raccourcis Clavier",
        "log_theme": "🎨 Thème appliqué :",
        "log_mode": "⚙️ Mode changé :",
        "log_lang": "🌍 Langue changée en Français",
        
        # Messages
        "msg_rec_start": "🔴 Enregistrement démarré",
        "msg_rec_end": "✅ Enregistrement terminé :",
        "msg_play_start": "▶ Lecture de la macro...",
        "msg_play_end": "⏸ Macro terminée",
        "msg_ghost_on": "👻 Mode Ghost activé (Appuyez sur F3 pour réafficher)",
        "msg_ghost_off": "👁️ Mode Ghost désactivé",
        "err_conflict_rec": "⚠️ Impossible d'enregistrer pendant la lecture !",
        "err_conflict_play": "⚠️ Impossible de lire pendant l'enregistrement !",
        "err_no_data": "Aucune macro en mémoire à lire."
    }
}
